- id: mdformat
  name: mdformat
  description: "CommonMark compliant Markdown formatter"
  entry: mdformat
  language: python
  language_version: python3
  types: [markdown]
  minimum_pre_commit_version: '1.0.0'
