- id: mdformat
  name: mdformat
  description: "CommonMark compliant Markdown formatter"
  entry: mdformat
  language: python
  # This is to support a use case where pre-commit runs in Python 2.
  # Should eventually be removed, at latest when `minimum_pre_commit_version`
  # is set to 2.0.0.
  language_version: python3
  types: [markdown]
  minimum_pre_commit_version: '1.0.0'
