contact_links:
  - name: Why does Mdformat use backslash to escape my Markdown engine specific syntax? ⁉️
    url: https://github.com/executablebooks/mdformat?tab=readme-ov-file#why-does-mdformat-backslash-escape-special-syntax-specific-to-mkdocs--hugo--obsidian--github--some-other-markdown-engine
    about: It's likely you need to install a plugin. See the FAQ more info.
